"""add_bloom_level_to_question

Revision ID: da3efef4a072
Revises: 859e46a842f2
Create Date: 2026-06-24 14:49:30.118916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'da3efef4a072'
down_revision: Union[str, Sequence[str], None] = '859e46a842f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('bloom_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='remember'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'bloom_level')
    # ### end Alembic commands ###
